
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Appraisal PDF</title>
</head>

<body>
<table cellspacing="0" cellpadding="12" width="800">
    <tr>
        <td>
            <table cellspacing="0" cellpadding="0" width="800">
                <tr>
                    <?php 
                        $organizationImg = new Zend_Session_Namespace('organizationinfo');
                        $orgLogoImg = MEDIA_PATH.'images/anritsu-logo.jpg';
                        /*if(isset($organizationImg->orgimg) && !empty($organizationImg->orgimg) && file_exists(BASE_PATH.'/uploads/organisation/'.$organizationImg->orgimg))
                        {
                            $orgLogoImg = DOMAIN.'public/uploads/organisation/'.$organizationImg->orgimg ; 
                        }*/
                    ?>
                    <td width="400"><img src="<?php echo $orgLogoImg; ?>"></td>
                    <td width="400" align="right"><font face="'Arial', sans-serif" size="3">Personal Review</font></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table border="0" cellpadding="8" cellspacing="0" width="800" style="border-collapse:collapse;">
                <tr>
                    <td width="150"><font face="'Arial', sans-serif" size="2">Name:</font></td>
                    <td width="250"><font face="'Arial', sans-serif" size="2"><strong><?php echo !empty($this->empAppraisalData[0]['userfullname'])?$this->empAppraisalData[0]['userfullname']:'';?></strong></font></td>
                    <td width="150"><font face="'Arial', sans-serif" size="2">Job Title:</font></td>
                    <td width="250"><font face="'Arial', sans-serif" size="2"><strong><?php echo !empty($this->empAppraisalData[0]['jobtitle_name'])?$this->empAppraisalData[0]['jobtitle_name']:'';?></strong></font></td>
                    
                    <!--<td width="150"><font face="'Arial', sans-serif" size="2">Business Unit:</font></td>
                    <td width="250"><font face="'Arial', sans-serif" size="2"><strong><?php echo !empty($this->empAppraisalData[0]['businessunit_name'])?$this->empAppraisalData[0]['businessunit_name']:'';?></strong></font></td>-->
                </tr>
                <!--<tr>
                    <td width="150"><font face="'Arial', sans-serif" size="2">Employee ID:</font></td>
                    <td width="250"><font face="'Arial', sans-serif" size="2"><strong><?php echo !empty($this->empAppraisalData[0]['employeeId'])?$this->empAppraisalData[0]['employeeId']:'';?></strong></font></td>
                    <td width="150"><font face="'Arial', sans-serif" size="2">Department:</font></td>
                    <td width="250"><font face="'Arial', sans-serif" size="2"><strong><?php echo !empty($this->empAppraisalData[0]['department_name'])?$this->empAppraisalData[0]['department_name']:'';?></strong></font></td>
                </tr>-->
                <tr>
                    <td width="150"><font face="'Arial', sans-serif" size="2">Review Mode:</font></td>
                    <td width="250"><font face="'Arial', sans-serif" size="2"><strong><?php echo !empty($this->empAppraisalData[0]['appraisal_mode'])?$this->empAppraisalData[0]['appraisal_mode']:'';?></strong></font></td>
                    <td width="150"><font face="'Arial', sans-serif" size="2">Review Year:</font></td>
                    <td width="250"><font face="'Arial', sans-serif" size="2"><strong><?php echo (!empty($this->empAppraisalData[0]['from_year']) && !empty($this->empAppraisalData[0]['to_year']))?($this->empAppraisalData[0]['from_year'].'-'.$this->empAppraisalData[0]['to_year']):'';?></strong></font></td>
                </tr>
                <!--<tr>
                    <td width="150"><font face="'Arial', sans-serif" size="2">Period:</font></td>
                    <td width="250" colspan="3"><font face="'Arial', sans-serif" size="2"><strong><?php echo !empty($this->appText)?$this->appText:'';?></strong></font></td>
                </tr>-->
            </table>
        </td>
    </tr>
    <?php
        $category_arr = !empty($this->data['category_arr'])?$this->data['category_arr']:array();
        $rating_arr = !empty($this->data['rating_arr'])?$this->data['rating_arr']:array();
        $employee_response = !empty($this->data['employee_response'])?$this->data['employee_response']:array();
        $manager_response = !empty($this->data['manager_response'])?$this->data['manager_response']:array();
        $employee_response_final = isset($this->data['employee_final_response'])?$this->data['employee_final_response']:'';
        $skill_arr = !empty($this->data['skill_arr'])?$this->data['skill_arr']:array();
        $ratings_data = !empty($this->data['ratings_data'])?$this->data['ratings_data']:array();
        $edit_flag = !empty($this->data['edit_flag'])?$this->data['edit_flag']:'';
        $skill_response = array();
        if(!empty($ratings_data['skill_response']))
        {
            $skill_response = json_decode($ratings_data['skill_response'],true);    
        }
        if(!empty($category_arr) || !empty($skill_response)) 
        { 
            //for categories and questions
            if(!empty($category_arr))
            {
                foreach($category_arr as  $key => $values)
                { 

                    ?>
                    <tr>
                        <td>
                            <font face="'Arial', sans-serif" size="3"><strong><?php echo $key;?></strong>
                                <?php
                                $achievement = false;
                                $rating = false;
                                $comment = false;
                                $objective = false;
                                foreach($values as $value){
                                    if(isset($value['question_type']) && in_array($value['question_type'],  array(QUESTION_TYPE_COMMENT_ACHIEVEMENT, QUESTION_TYPE_OBJECTIVE))){
                                        $achievement = true;
                                    }
                                    if(isset($value['question_type']) && in_array($value['question_type'], array(QUESTION_TYPE_RATINGONLY, QUESTION_TYPE_COMMENT_RATING)) ){
                                        $rating = true;
                                    }
                                    if(isset($value['question_type']) && in_array($value['question_type'], array(QUESTION_TYPE_COMMENT_RATING, QUESTION_TYPE_COMMENTONLY, QUESTION_TYPE_COMMENT_ACHIEVEMENT, QUESTION_TYPE_OBJECTIVE)) ){
                                        $comment = true;
                                    }
                                    if(isset($value['question_type']) && $value['question_type']==QUESTION_TYPE_OBJECTIVE){
                                        $objective = true;
                                    }
                                }
                                if($achievement)
                                    echo "(A = Achieved – PA = Partially Achieved – NA = Not Achieved)";
                                ?>
                            </font>
                            <table border="1" cellpadding="8" cellspacing="0" width="800" style="border-collapse:collapse; margin-top: 10px;">
                                <?php if($rating && $comment && !$achievement){ ?>
                                    <tr>
                                        <td width="300"><font face="'Arial', sans-serif" size="2"><strong>Question</strong></font></td>
                                        <td width="250"><font face="'Arial', sans-serif" size="2"><strong>Employee Comment</strong></font></td>
                                        <td width="250"><font face="'Arial', sans-serif" size="2"><strong>Manager Comment</strong></font></td>
                                    </tr>
                                <?php } elseif($objective){ ?>
                                    <tr>
                                        <td colspan="1"></td>
                                        <td colspan="4" align="center"><font face="'Arial', sans-serif" size="2">Employee</font></td>
                                        <td colspan="4" align="center"><font face="'Arial', sans-serif" size="2">Manager</font></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td align="center"><font face="'Arial', sans-serif" size="2"><strong>NA</strong></font></td>
                                        <td align="center"><font face="'Arial', sans-serif" size="2"><strong>PA</strong></font></td>
                                        <td align="center"><font face="'Arial', sans-serif" size="2"><strong>A</strong></font></td>
                                        <td align="center"><font face="'Arial', sans-serif" size="2"><strong>Comments</strong></font></td>
                                        <td align="center"><font face="'Arial', sans-serif" size="2"><strong>NA</strong></font></td>
                                        <td align="center"><font face="'Arial', sans-serif" size="2"><strong>PA</strong></font></td>
                                        <td align="center"><font face="'Arial', sans-serif" size="2"><strong>A</strong></font></td>
                                        <td align="center"><font face="'Arial', sans-serif" size="2"><strong>Comments</strong></font></td>
                                    </tr>
                                <?php } else if($achievement){ ?>
                                    <tr>
                                        <td></td>
                                        <td align="center"><font face="'Arial', sans-serif" size="2"><strong>NA</strong></font></td>
                                        <td align="center"><font face="'Arial', sans-serif" size="2"><strong>PA</strong></font></td>
                                        <td align="center"><font face="'Arial', sans-serif" size="2"><strong>A</strong></font></td>
                                        <td align="center"><font face="'Arial', sans-serif" size="2"><strong>Comments</strong></font></td>
                                    </tr>
                                <?php } ?>
                                <?php
                                if(!empty($values))
                                {
                                    foreach($values as $k=>$v)
                                    { 
                                        $qrating = (isset($v['question_id']) && isset($manager_response[$v['question_id']]))?$manager_response[$v['question_id']]['rating']:"";
                                        $qcomment = (isset($v['question_id']) && isset($manager_response[$v['question_id']]))?$manager_response[$v['question_id']]['comment']:"";
                                        $qachievement = (isset($v['question_id']) && isset($manager_response[$v['question_id']]))?$manager_response[$v['question_id']]['achievement']:"";

                                        $emprating = (isset($v['question_id']) && isset($employee_response[$v['question_id']]))?$employee_response[$v['question_id']]['rating']:"";
                                        $empcomment = (isset($v['question_id']) && isset($employee_response[$v['question_id']]))?$employee_response[$v['question_id']]['comment']:"";
                                        $empachievement = (isset($v['question_id']) && isset($employee_response[$v['question_id']]))?$employee_response[$v['question_id']]['achievement']:"";
                                        $empobjective = (isset($v['question_id']) && isset($employee_response[$v['question_id']]))?$employee_response[$v['question_id']]['objective']:"";

                                        ?>
                                    <tr>
                                        <?php if($v['question_type'] == QUESTION_TYPE_OBJECTIVE) {
                                            if($empobjective != ''){ ?>
                                                <td width="200"  valign="top"><font face="'Arial', sans-serif" size="2"><strong><?php echo isset($v['question'])?$v['question']:'';?></strong></font>
                                                    <br>
                                                    <font face="'Arial', sans-serif" size="1"><?php echo $empobjective;?></font>
                                                </td>
                                                <td width="30"  valign="top" align="center">
                                                    <input type="checkbox" <?php if($empachievement == "Not Achieved"){echo "checked='checked'";} ?>/>
                                                </td>
                                                <td width="30"  valign="top" align="center">
                                                    <input type="checkbox" <?php if($empachievement == "Partially Achieved"){echo "checked='checked'";} ?>/>
                                                </td>
                                                <td width="30"  valign="top" align="center">
                                                    <input type="checkbox" <?php if($empachievement == "Achieved"){echo "checked='checked'";} ?>/>
                                                </td>
                                                <td width="210" valign="top">
                                                    <?php if(($this->empAppraisalData[0]['appraisal_status'] != 'Pending L1 ratings' && $this->empAppraisalData[0]['appraisal_status'] != 'Pending employee ratings')  || ($this->empAppraisalData[0]['line_manager_1'] == $this->loginUserId)) {?>
                                                        <font face="'Arial', sans-serif" size="2"><?php echo !empty($empcomment)?$empcomment:'';?></font>
                                                    <?php } ?>
                                                </td>
                                                <td width="30"  valign="top" align="center">
                                                    <input type="checkbox" <?php if($qachievement == "Not Achieved"){echo "checked='checked'";} ?>/>
                                                </td>
                                                <td width="30"  valign="top" align="center">
                                                    <input type="checkbox" <?php if($qachievement == "Partially Achieved"){echo "checked='checked'";} ?>/>
                                                </td>
                                                <td width="30"  valign="top" align="center">
                                                    <input type="checkbox" <?php if($qachievement == "Achieved"){echo "checked='checked'";} ?>/>
                                                </td>
                                                <td width="210" valign="top">
                                                    <?php if(($this->empAppraisalData[0]['appraisal_status'] != 'Pending L1 ratings' && $this->empAppraisalData[0]['appraisal_status'] != 'Pending employee ratings')  || ($this->empAppraisalData[0]['line_manager_1'] == $this->loginUserId)) {?>
                                                        <font face="'Arial', sans-serif" size="2"><?php echo !empty($qcomment)?$qcomment:'';?></font>
                                                    <?php } ?>
                                                </td>
                                        <?php }} else if($rating && $comment && !$achievement){ ?>
                                            <td width="300"  valign="top"><font face="'Arial', sans-serif" size="2"><strong><?php echo isset($v['question'])?$v['question']:'';?></strong></font>
                                                <br>
                                                <br>
                                                <font face="'Arial', sans-serif" size="1"><?php echo isset($v['description'])?$v['description']:'';?></font>
                                            </td>
                                            <td width="250"  valign="top">
                                                <font face="'Arial', sans-serif" size="3"><strong><?php echo (isset($v['question_id']) && isset($rating_arr[$employee_response[$v['question_id']]['rating_id']]))?$rating_arr[$employee_response[$v['question_id']]['rating_id']]['rating_value'].' - ':"";?></strong></font>
                                                <font face="'Arial', sans-serif" size="1"><?php echo (isset($v['question_id']) && isset($rating_arr[$employee_response[$v['question_id']]['rating_id']]))?$rating_arr[$employee_response[$v['question_id']]['rating_id']]['rating_text']:"";?></font>
                                                <br>
                                                <br>

                                                <font face="'Arial', sans-serif" size="1"><?php echo (isset($v['question_id']) && !empty($employee_response[$v['question_id']]['comment']))?$employee_response[$v['question_id']]['comment']:'';?></font>
                                            </td>
                                            <td width="250"  valign="top">
                                                <?php if(($this->empAppraisalData[0]['appraisal_status'] != 'Pending L1 ratings' && $this->empAppraisalData[0]['appraisal_status'] != 'Pending employee ratings')  || ($this->empAppraisalData[0]['line_manager_1'] == $this->loginUserId)) {?>
                                                    <font face="'Arial', sans-serif" size="3"><strong><?php echo (isset($rating_arr[$qrating]))?$rating_arr[$qrating]['rating_value'].' - ':'';?></strong></font>
                                                    <font face="'Arial', sans-serif" size="1"><?php echo (isset($rating_arr[$qrating]))?$rating_arr[$manager_response[$v['question_id']]['rating']]['rating_text']:"";?></font>
                                                    <br>
                                                    <br>
                                                    <font face="'Arial', sans-serif" size="1"><?php echo !empty($qcomment)?$qcomment:'';?></font>
                                                <?php } ?>
                                            </td>
                                        <?php } elseif($achievement){ ?>
                                            <td width="150"  valign="top"><font face="'Arial', sans-serif" size="2"><strong><?php echo isset($v['question'])?$v['question']:'';?></strong></font>
                                                <br>
                                                <br>
                                                <font face="'Arial', sans-serif" size="1"><?php echo isset($v['description'])?$v['description']:'';?></font>
                                            </td>
                                            <td width="30"  valign="top" align="center">
                                                <input type="checkbox" <?php if($qachievement == "Not Achieved"){echo "checked='checked'";} ?>/>
                                            </td>
                                            <td width="30"  valign="top" align="center">
                                                <input type="checkbox" <?php if($qachievement == "Partially Achieved"){echo "checked='checked'";} ?>/>
                                            </td>
                                            <td width="30"  valign="top" align="center">
                                                <input type="checkbox" <?php if($qachievement == "Achieved"){echo "checked='checked'";} ?>/>
                                            </td>
                                            <td width="450"  valign="top">
                                                <?php if(($this->empAppraisalData[0]['appraisal_status'] != 'Pending L1 ratings' && $this->empAppraisalData[0]['appraisal_status'] != 'Pending employee ratings')  || ($this->empAppraisalData[0]['line_manager_1'] == $this->loginUserId)) {?>
                                                    <font face="'Arial', sans-serif" size="2"><?php echo !empty($qcomment)?$qcomment:'';?></font>
                                                <?php } ?>
                                            </td>
                                        <?php } elseif($rating && !$comment && !$achievement){ ?>
                                            <td valign="top" align="center">
                                                <font face="'Arial', sans-serif" size="5"><strong><?php echo (isset($rating_arr[$qrating]))?$rating_arr[$qrating]['rating_value'].' - ':'';?></strong></font>
                                                <font face="'Arial', sans-serif" size="3"><?php echo (isset($rating_arr[$qrating]))?$rating_arr[$manager_response[$v['question_id']]['rating']]['rating_text']:"";?></font>
                                            </td>
                                        <?php } else {
                                            $managerComment = empty($qcomment)?'':$qcomment;
                                            $employeeComment = (isset($v['question_id']) && !empty($employee_response[$v['question_id']]['comment']))?$employee_response[$v['question_id']]['comment']:'';
                                            if(strlen($managerComment) > 0 && strlen($employeeComment) > 0) { ?>
                                                <td valign="top" width="50%" style="height:100px;">
                                                    <font face="'Arial', sans-serif" size="2">Employee: <?php echo $employeeComment; ?></font>
                                                </td>
                                                <td valign="top" width="50%" style="height:100px;">
                                                    <font face="'Arial', sans-serif" size="2">Manager: <?php echo $managerComment; ?></font>
                                                </td>
                                        <?php } elseif(strlen($managerComment) > 0){ ?>
                                                <td valign="top" style="height:100px ;">
                                                    <font face="'Arial', sans-serif" size="2"><?php echo $managerComment; ?></font>
                                                </td>
                                        <?php } elseif(strlen($employeeComment) > 0){ ?>
                                                <td valign="top" style="height:100px ;">
                                                    <font face="'Arial', sans-serif" size="2"><?php echo $employeeComment; ?></font>
                                                </td>
                                            <?php } else {
                                                echo "<td style='height:100px'></td>";
                                            }
                                        } ?>

                                    </tr>
                                    <?php
                                    }
                                }
                                ?>
                            </table>
                        </td>
                    </tr>
                <?php
                }
            }
            //final emp response ?>
            <tr>
                <td>
                    <font face="'Arial', sans-serif" size="3"><strong>Final Employee Feedback</strong></font>

                    <table border="1" cellpadding="8" cellspacing="0" width="800" style="border-collapse:collapse; margin-top: 10px;">
                        <tr>
                            <td valign="top" style="height:100px ;">
                                <font face="'Arial', sans-serif" size="2"><?php echo $employee_response_final; ?></font>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <?php
            //for skills
            $skill_id_arr = array();
            foreach($skill_arr as $skill_id => $skill_name)
            {
                $skill_id_arr[$skill_id] = $skill_name;
            }               
                if(!empty($ratings_data['skill_response']) && (($this->empAppraisalData[0]['appraisal_status'] != 'Pending L1 ratings' && $this->empAppraisalData[0]['appraisal_status'] != 'Pending employee ratings' )  || ($this->empAppraisalData[0]['line_manager_1'] == $this->loginUserId)))
                {
                    $skill_response = json_decode($ratings_data['skill_response'],true);
                    if(count($skill_response) > 0 && !empty($skill_response))
                    {
            ?>
                    <tr>
                        <td><font face="'Arial', sans-serif" size="3"><strong>Skill Set</strong></td>
                    </tr>
                    <tr>
                        <td>
                            <table border="1" cellpadding="8" cellspacing="0" width="800" style="border-collapse:collapse;">
                                <tr>
                                    <td width="400"><font face="'Arial', sans-serif" size="2"><strong>Skill</strong></font></td>                        
                                    <td width="400"><font face="'Arial', sans-serif" size="2"><strong>Rating</strong></font></td>  
                                </tr>
                                <?php
                                    foreach($skill_response as $sk_id => $sk_rating)
                                    {
                                ?>
                                        <tr>
                                            <td width="400"><font face="'Arial', sans-serif" size="2"><strong><?php echo isset($skill_id_arr[$sk_id])?$skill_id_arr[$sk_id]:'';?></strong></font></td>
                                            <td width="400">
                                                <span class="rating_value"><font face="'Arial', sans-serif" size="3"><strong><?php echo isset($rating_arr[$sk_rating]['rating_value'])?$rating_arr[$sk_rating]['rating_value'].' - ':'';?></strong></font></span>
                                                <span class="rating_txt"><font face="'Arial', sans-serif" size="1"><?php echo isset($rating_arr[$sk_rating]['rating_text'])?$rating_arr[$sk_rating]['rating_text']:'';?></font></span>
                                            </td> 
                                        </tr>   
                                <?php
                                    } ?>
                            </table>
                        </td>
                    </tr>
                    <?php 
                }
            }
        }
    $empAgreed = false;
    $manAgreed = false;
    switch($this->empAppraisalData[0]['appraisal_status']){
        case 'Pending employee ratings':
            break;
        case 'Pending L1 ratings':
            $empAgreed = true;
            break;
        default:
            $empAgreed = true;
            $manAgreed = true;
            break;
    }
    ?>
    <tr>
        <td>
            <table border="1" cellpadding="8" cellspacing="0" width="800" style="border-collapse:collapse; margin-top: 10px;">
                <tr>
                    <td valign="top" style="height:50px ;">
                        <input type="checkbox" <?php if($empAgreed) echo "checked='checked'"; ?>/>
                        <font face="'Arial', sans-serif" size="2"><?php echo $this->empAppraisalData[0]['userfullname']." on ".$this->historyData['employeeSubmitted']." - ".APPRAISAL_AGREEMENT_TEXT; ?>
                        </font>
                    </td>
                </tr>
                <tr>
                    <td valign="top" style="height:50px ;" >
                        <input type="checkbox" <?php if($manAgreed) echo "checked='checked'"; ?>/>
                        <font face="'Arial', sans-serif" size="2"><?php echo $this->data['manager_name']." on ".$this->historyData['managerSubmitted']." - ".APPRAISAL_AGREEMENT_TEXT; ?>
                        </font>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>

</html>